---
# Stat the named.conf and IPA default.conf file, if the file exists, then IPA is already configured.


#We have added the needed repo and download the packages
- name: adding epel repo
  package: name={{item}} state=installed
  with_items:
    - epel-release


- name: adding required freeipa packages
  package: name={{item}} state=installed
  with_items:
    - bind
    - bind-utils
    - ipa-server
    - ipa-server-dns
    - rng-tools

#This is the easist method so far to set fqdn, it reset after reboot though, FreeIPA needs an FQDN.
# https://unix.stackexchange.com/questions/239920/how-to-set-the-fully-qualified-hostname-on-centos-7-0

- name: Setting hostname via hostnamectl
  command: hostnamectl set-hostname {{ ansible_hostname }}.{{domain}}


#We install rngd because we need to ensure there is enough entropy to
#generate the initial keys. /dev/random sometimes runs out.
- service:
    name: rngd
    state: started
    enabled: yes

#I need to make sure that i perform a check before editing file
#/usr/lib/python2.7/site-packages/ipapython/ipautil.py
# On GCP we need to make sure we delete the IP host checking.
#
#This is the purpsoe of the following bit of code. It removes that check.
#
# ipa-server-install --unattended --ip-address={{ ansible_default_ipv4.address }}  --ca-signing-algorithm=SHA512withRSA --no-ui-redirect --realm=lab --ds-password=Kn0wledge2143 --admin-password=Kn0wledge2143 --setup-dns --forwarder=8.8.8.8 --forwarder=8.8.4.4
#  shell: "/usr/bin/sed -i '202,206d' /usr/lib/python2.7/site-packages/ipapython/ipautil.py"

- name: installing freeipa
  command: ipa-server-install --unattended --ip-address={{ ansible_default_ipv4.address }}  --ca-signing-algorithm={{ ca_signing_algo }} --no-ui-redirect --realm={{domain}} --ds-password={{dsmgr_password}} --admin-password={{admin_password}} --setup-dns --forwarder={{ IPA_DNS_Forwarder }}
