---
domain: "{{ lookup('env','DOMAIN') | default('motherbase.ops',true) }}"
dsmgr_password: "{{ lookup('env','MGR_PASS') | default('Fr33IPA#DS#MGR',true) }}"
admin_password: "{{ lookup('env','ADMIN_PASS') | default('Fr33IPA#DS#Admin',true) }}"
ca_signing_algo: "{{ lookup('env','CA_SIGNING_ALGO') | default('SHA512withRSA',true) }}" 
admin_user: "{{ lookup('env','ADMIN_USER') | default('admin',true) }}"
IPA_DNS_Forwarder: 8.8.8.8

# defaults file for freeipa-client

freeipaclient_enable_ntp: true
freeipaclient_all_ip_addresses: "{{ true if ansible_distribution_release != 'trusty' else false }}"
freeipaclient_enable_dns_updates: true
freeipaclient_force_join: true
freeipaclient_server: ctrlmaster.motherbase.ops
freeipaclient_domain: motherbase.ops
freeipa_dns_server: 192.168.3.2
freeipaclient_enroll_user: admin
freeipaclient_enroll_pass: "{{ admin_password }}"
client_provision: False



#This is where the user variables are generally defined.
#these are the defaults I suppose
ipa_groups:
    - name: "offensive"
      state: "present"

    - name: "defensive"
      state: "present"

    - name: "support"
      state: "present"


ipa_users:
   - name: "m3rl1n th31nitiate"
     username: "m3rl1n"
     password: "m3rl1npass" 
     state: "present"
     surename: "th31nitiate"
     groups: ['admins']
     home: "/home/m3rl1n/"
     ssh_key:
       - "ssh-rsa AAAAB3NzaDqRoDzNZEfP4mVY156lECghNc2lxR7WXtPb3WOGqntqHetC69tb8JTUmZ8k/DSfBvcztt/7Ua9Q6jFELco/GVYpDgoQ8fnty8bgbEKQM/WEte/cKgi2njUhjaCNvy25wxQhu+l3ukaBEEonNTtxlqug8xvlmmiRoQdJeOM/Vnmnxy6rmsGJ8ZOA7+e3wWROBQV0q7t36c2j m3rl1n@th3-Arch"






