---
- hosts: ctrlmaster
  become: yes
  vars:
  roles:
    - motherbase.freeipa
  tasks:

- hosts: ctrlslave
  become: yes
  vars:
    client_provision: True
  roles:
    - motherbase.freeipa
  tasks: