driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: gcp-boot-strap
  # This can be used to define the cloud provider so you have one for each provider

suites:
  - name: example
